<a href="https://colab.research.google.com/github/tranviviana/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)



2.3.1+cu121




```
# This is formatted as code
```

###**Introduction to Tensors**###


Creating Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim


0

In [5]:
#conver tensor to python int
scalar.item()

7

In [6]:
#vector notation
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
#dimension correlates to number of square brackets
vector.ndim

1

In [8]:
#number of elements in square brackets
vector.shape

torch.Size([2])

In [9]:
vector2 = torch.tensor([7,7,7,7])
vector2

tensor([7, 7, 7, 7])

In [10]:
vector2.ndim

1

In [11]:
vector2.shape

torch.Size([4])

In [12]:
# matrix styles
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX[0][0]

tensor(7)

In [16]:
MATRIX[0][0].item()


7

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
#tensors
TENSOR = torch.tensor([[[1,2,3], [3,6,9], [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
#outermost bracket matches here
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [22]:
TENSOR[0][1]

tensor([3, 6, 9])

In [23]:
TENSOR2 = torch.tensor([[[[1,2,3,8],[7,4,5,6],[2,3,4,5],[2,3,0,5]]]])
TENSOR2

tensor([[[[1, 2, 3, 8],
          [7, 4, 5, 6],
          [2, 3, 4, 5],
          [2, 3, 0, 5]]]])

In [24]:
TENSOR2.ndim

4

In [25]:
TENSOR2.shape

torch.Size([1, 1, 4, 4])

In [26]:
TENSOR2[0]

tensor([[[1, 2, 3, 8],
         [7, 4, 5, 6],
         [2, 3, 4, 5],
         [2, 3, 0, 5]]])

In [27]:
TENSOR2[0][0]

tensor([[1, 2, 3, 8],
        [7, 4, 5, 6],
        [2, 3, 4, 5],
        [2, 3, 0, 5]])

In [28]:
TENSOR2[0][0][0]

tensor([1, 2, 3, 8])

###**CREATING RANDOM TENSORS**###

random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data`

In [29]:
#creating random tensors of size(3,4)
random_tensor = torch.rand(8,2,2) #8 groups of 2 by 2
random_tensor


tensor([[[0.8105, 0.4665],
         [0.5998, 0.9051]],

        [[0.7949, 0.1697],
         [0.2014, 0.3052]],

        [[0.2484, 0.9814],
         [0.0153, 0.7170]],

        [[0.5171, 0.1944],
         [0.1353, 0.1021]],

        [[0.3964, 0.6666],
         [0.1306, 0.6181]],

        [[0.7673, 0.7517],
         [0.5445, 0.6178]],

        [[0.0222, 0.6047],
         [0.2369, 0.9363]],

        [[0.8411, 0.2154],
         [0.2638, 0.8021]]])

In [30]:
random_tensor.ndim,random_tensor[0]

(3,
 tensor([[0.8105, 0.4665],
         [0.5998, 0.9051]]))

In [31]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height width color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [32]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [33]:
tensor.ndim

1

In [34]:
tensor[0]

tensor(1)

###**Zeros and Ones**###

In [35]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7469, 0.6840, 0.1079, 0.5863],
        [0.9741, 0.0919, 0.0779, 0.6911],
        [0.7828, 0.9233, 0.4064, 0.7623]])

In [37]:
random_tensor * zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
#defaults to floats (controlled by d types)
ones.dtype

torch.float32

Creating a Range of Tensors and tensors-like

In [40]:
torch.range(0,10)
#use aragnge inclusive - exclusive, step
one_to_ten = torch.arange(0,1000,77)
one_to_ten

<ipython-input-40-1a141de359bf>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [41]:
#creating tensors like: making it the same shape

In [42]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###**Tensor Datatypes**###
**Note:** Tensor datatypes is one of the 3 big errors you'll run int:
 1: Tensors not right datatype (SOME)
 2: Tensors not right shape
 3: Tensors not on the right device


In [43]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None,
                               device=None,
                               requires_grad=False) #whether or not to track gradients)
float_32_tensor
#this is the device section^

tensor([3., 6., 9.])

In [44]:
float_32_tensor.dtype

torch.float32

In [45]:
float_16_tensor = float_32_tensor.type(torch.torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [46]:
combined_float = float_16_tensor * float_32_tensor

In [47]:
combined_float.dtype

torch.float32

### getting information from tensors

1. datatype - tensor.dtype
2. shape - tensor.shape
3. device - tensor.device

In [48]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1565, 0.0923, 0.7145, 0.0259],
        [0.2964, 0.7502, 0.7116, 0.6649],
        [0.9986, 0.1374, 0.1599, 0.7663]])

In [49]:
print(f"the type is {some_tensor.dtype}; the shape is {some_tensor.shape} and the device is {some_tensor.device} can say the size if function {some_tensor.size()}")

the type is torch.float32; the shape is torch.Size([3, 4]) and the device is cpu can say the size if function torch.Size([3, 4])


### Manipulating Tensors (tensor operations)

Addition, Subtraction, element-wise multiplication, division, matrix multiplication

In [51]:
#create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [53]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

###MATRIC MULTIPLICATION

1) element-wise
2) matrix multiplication

In [54]:
#element wise
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [56]:
torch.matmul(tensor, tensor)

tensor(14)