<a href="https://colab.research.google.com/github/tranviviana/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)



2.3.1+cu121




```
# This is formatted as code
```

###**Introduction to Tensors**###


Creating Tensors

In [2]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim


0

In [4]:
#conver tensor to python int
scalar.item()

7

In [5]:
#vector notation
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
#dimension correlates to number of square brackets
vector.ndim

1

In [7]:
#number of elements in square brackets
vector.shape

torch.Size([2])

In [8]:
vector2 = torch.tensor([7,7,7,7])
vector2

tensor([7, 7, 7, 7])

In [9]:
vector2.ndim

1

In [10]:
vector2.shape

torch.Size([4])

In [11]:
# matrix styles
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX[0][0]

tensor(7)

In [15]:
MATRIX[0][0].item()


7

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
#tensors
TENSOR = torch.tensor([[[1,2,3], [3,6,9], [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
#outermost bracket matches here
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [21]:
TENSOR[0][1]

tensor([3, 6, 9])

In [22]:
TENSOR2 = torch.tensor([[[[1,2,3,8],[7,4,5,6],[2,3,4,5],[2,3,0,5]]]])
TENSOR2

tensor([[[[1, 2, 3, 8],
          [7, 4, 5, 6],
          [2, 3, 4, 5],
          [2, 3, 0, 5]]]])

In [23]:
TENSOR2.ndim

4

In [24]:
TENSOR2.shape

torch.Size([1, 1, 4, 4])

In [25]:
TENSOR2[0]

tensor([[[1, 2, 3, 8],
         [7, 4, 5, 6],
         [2, 3, 4, 5],
         [2, 3, 0, 5]]])

In [26]:
TENSOR2[0][0]

tensor([[1, 2, 3, 8],
        [7, 4, 5, 6],
        [2, 3, 4, 5],
        [2, 3, 0, 5]])

In [27]:
TENSOR2[0][0][0]

tensor([1, 2, 3, 8])

###**CREATING RANDOM TENSORS**###

random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data`

In [28]:
#creating random tensors of size(3,4)
random_tensor = torch.rand(8,2,2) #8 groups of 2 by 2
random_tensor


tensor([[[0.4855, 0.7746],
         [0.2785, 0.3421]],

        [[0.6158, 0.8285],
         [0.4654, 0.9152]],

        [[0.4275, 0.1909],
         [0.1211, 0.6692]],

        [[0.3412, 0.5528],
         [0.5702, 0.6553]],

        [[0.9285, 0.5904],
         [0.1883, 0.9897]],

        [[0.8491, 0.0813],
         [0.2921, 0.2034]],

        [[0.0188, 0.0339],
         [0.0195, 0.8666]],

        [[0.4643, 0.8409],
         [0.1792, 0.0239]]])

In [29]:
random_tensor.ndim,random_tensor[0]

(3,
 tensor([[0.4855, 0.7746],
         [0.2785, 0.3421]]))

In [30]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height width color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [31]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [32]:
tensor.ndim

1

In [33]:
tensor[0]

tensor(1)

###**Zeros and Ones**###

In [34]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6374, 0.5247, 0.3907, 0.4054],
        [0.2459, 0.9650, 0.7908, 0.7136],
        [0.4701, 0.7552, 0.3254, 0.0113]])

In [36]:
random_tensor * zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
#defaults to floats (controlled by d types)
ones.dtype

torch.float32

Creating a Range of Tensors and tensors-like

In [39]:
torch.range(0,10)
#use aragnge inclusive - exclusive, step
one_to_ten = torch.arange(0,1000,77)
one_to_ten

<ipython-input-39-1a141de359bf>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [40]:
#creating tensors like: making it the same shape

In [41]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###**Tensor Datatypes**###
**Note:** Tensor datatypes is one of the 3 big errors you'll run int:
 1: Tensors not right datatype (SOME)
 2: Tensors not right shape
 3: Tensors not on the right device


In [42]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None,
                               device=None,
                               requires_grad=False) #whether or not to track gradients)
float_32_tensor
#this is the device section^

tensor([3., 6., 9.])

In [43]:
float_32_tensor.dtype

torch.float32

In [44]:
float_16_tensor = float_32_tensor.type(torch.torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
combined_float = float_16_tensor * float_32_tensor

In [46]:
combined_float.dtype

torch.float32

### getting information from tensors

1. datatype - tensor.dtype
2. shape - tensor.shape
3. device - tensor.device

In [47]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3067, 0.3183, 0.4147, 0.8732],
        [0.0618, 0.2145, 0.6281, 0.0769],
        [0.1575, 0.3900, 0.1019, 0.9507]])

In [48]:
print(f"the type is {some_tensor.dtype}; the shape is {some_tensor.shape} and the device is {some_tensor.device} can say the size if function {some_tensor.size()}")

the type is torch.float32; the shape is torch.Size([3, 4]) and the device is cpu can say the size if function torch.Size([3, 4])


### Manipulating Tensors (tensor operations)

Addition, Subtraction, element-wise multiplication, division, matrix multiplication

In [49]:
#create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [50]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

###MATRIC MULTIPLICATION

1) element-wise
2) matrix multiplication

In [51]:
#element wise
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [52]:
torch.matmul(tensor, tensor)
#tensor @ tensor
#torch.mm(tensor_A,tensor_B)

tensor(14)

In [53]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                         [9,12]])
tensor_A.shape

torch.Size([3, 2])

In [54]:
tensor_B.T


tensor([[ 7,  8,  9],
        [10, 11, 12]])

###FIND the min, max,mean,sum, etc (aggregation)



In [55]:
x = torch.arange(0,100,10)

In [56]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [57]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [58]:
x.dtype

torch.int64

In [59]:
torch.mean(x.type(torch.float32))
#cast as a float32


tensor(45.)

In [60]:
x.sum()

tensor(450)

###Finding the positional min and max of tensors

In [108]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [110]:
x.argmin(), x[0]

(tensor(0), tensor(1))

In [63]:
x.argmax(), x[len(x) - 1]

(tensor(9), tensor(91))

###Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - returns a certain shape **but does not store it**
* Stacking - combine multiple tensors on top of each other (vstack or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [64]:
import torch
x = torch.arange(1.,10.)

x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [65]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [66]:
z = x.view(1,9)
z, z.shape
#like an array view shares same memory

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
#splicing
z[:,2] = 5
z,x


(tensor([[1., 2., 5., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 5., 4., 5., 6., 7., 8., 9.]))

In [68]:
q = x.view(3,3)
q, q.shape


(tensor([[1., 2., 5.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [69]:
q[0,0] = 4
q, x, z

(tensor([[4., 2., 5.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([4., 2., 5., 4., 5., 6., 7., 8., 9.]),
 tensor([[4., 2., 5., 4., 5., 6., 7., 8., 9.]]))

In [70]:
#stacks on top of each other
x_stacked = torch.stack([x,x,x,x,x], dim = 1)
x_stacked

tensor([[4., 4., 4., 4., 4.],
        [2., 2., 2., 2., 2.],
        [5., 5., 5., 5., 5.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [71]:
#squeezing and unsqueezing
x_reshaped[0, 0] = 5
x_reshaped = x_reshaped.reshape(1,9)
x_reshaped[0,2] = 3
x_reshaped[0,3] = 4
x_reshaped[0,len(x_reshaped[0]) - 3] = 7
x_reshaped[0,len(x_reshaped[0]) - 2] = 8
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [72]:
#torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
#removing dimensions
x_squeezed = x_reshaped.squeeze(-2)
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")
x_reshaped.squeeze(), x_reshaped.squeeze().shape

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [73]:
# torch. unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
#removing dimensions
x_unsqueezed = x_squeezed.unsqueeze(0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [74]:
#torch.permut - returns a view that is rearranged in dimensions
x_original = torch.rand(size=(224,224,3)) #height width, color
x_original
#permute the og to rearrange the axis order
x_permute = x_original.permute(2,0,1) #0->1 1->2 2-> 0
x_permute.shape, x_original.shape

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

###INDEXING


In [75]:
#crate a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape
#1 is the outer bracket 3 is the 3 rows with 3 elements

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [76]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
x[0][0]

tensor([1, 2, 3])

In [78]:
x[0][0][0]

tensor(1)

In [79]:
y = torch.arange(1,11)
y.reshape(2,1,5)

tensor([[[ 1,  2,  3,  4,  5]],

        [[ 6,  7,  8,  9, 10]]])

In [80]:
x[0][2][2]

tensor(9)

In [81]:
#get all 0th and 1st dimension but only index 1 of secon dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [82]:
# get all 0 but only 1 of 1 and2 dimension
x[:,1,1]
x[0][1][1]

tensor(5)

In [83]:


x[:,:,2]

tensor([[3, 6, 9]])

In [84]:
x[0][2][2]

tensor(9)

Tensors and numpy

Numpy: numerical computing library
data in numpy -> pytorch tensor == torch.from_numpy(ndarray) (gives u 32 when usually 64)
tensor-> numpy==torch.Tensor.numpy (gives u 64 when torch usually 32)

In [85]:
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [86]:
array[0] = 1
array = array + 1
array, tensor
#indexing changes value but + 1 doesnt

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [88]:
tensor.dtype

torch.float32

In [89]:
numpy_tensor.dtype

dtype('float32')

In [90]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility
aka neural nets take random and keep testing against self through tensor operations


In [91]:
import torch
#create a random seed
#set seed everytime
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3,4)


torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3,4)
print(random_C)
print(random_D)
print(random_C == random_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and Pytorch objets on the GPUs (and making faster computations)


In [93]:
!nvidia-smi

Thu Aug  8 22:42:17 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2 check for GPU access with PyTorch

In [95]:
import torch
torch.cuda.is_available()

True

In [98]:
#setup device agnostic code if its available use a gpa
if torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"

In [102]:
device

'cuda'

In [100]:
#count number of devices
torch.cuda.device_count()

1

###Puttings tensors and models on GPU
to make it faster

In [103]:
tensor = torch.tensor([1,2,3], device="cpu")
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [105]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [107]:
tensor_back_cpu = tensor_on_gpu.cpu()
tensor_back_cpu.numpy()

array([1, 2, 3])

###PRACTICE


In [114]:
import torch
x = torch.rand(7,7)
x

tensor([[0.2297, 0.9545, 0.6099, 0.5643, 0.0594, 0.7099, 0.4250],
        [0.2709, 0.9295, 0.6115, 0.2234, 0.2469, 0.4761, 0.7792],
        [0.3722, 0.2147, 0.3288, 0.1265, 0.6783, 0.8870, 0.0293],
        [0.6161, 0.7583, 0.5907, 0.3219, 0.7610, 0.7628, 0.6870],
        [0.4121, 0.3676, 0.5535, 0.4117, 0.3510, 0.8196, 0.9297],
        [0.4505, 0.3881, 0.5073, 0.4701, 0.6202, 0.6401, 0.0459],
        [0.3155, 0.9211, 0.6948, 0.4751, 0.1985, 0.1941, 0.0521]])

In [121]:
y = torch.rand(1,7)
print(y)
y = torch.permute(y,(1,0))
print(y)

tensor([[0.3396, 0.1332, 0.4118, 0.2576, 0.3470, 0.0240, 0.7797]])
tensor([[0.3396],
        [0.1332],
        [0.4118],
        [0.2576],
        [0.3470],
        [0.0240],
        [0.7797]])


In [122]:
z = torch.matmul(x,y)
z

tensor([[0.9707],
        [1.2299],
        [0.6025],
        [1.4545],
        [1.3893],
        [0.8011],
        [0.7525]])

In [123]:
torch.manual_seed(0)
x = torch.rand(7,7)
torch.manual_seed(0)
y = torch.rand(1,7)
y = torch.permute(y,(1,0))
z = torch.matmul(x,y)
print(z)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


In [126]:
print(torch.cuda.manual_seed(1234))

None


In [140]:
torch.manual_seed(1234)
x = torch.rand(2,3)

gpu_x = x.to(device)
y = torch.rand(2,3)
gpu_y = y.to(device)
gpu_x, gpu_y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [141]:
z = torch.matmul(gpu_x, gpu_y.T)

In [142]:
max = torch.max(z)
min = torch.min(z)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [143]:
max = torch.argmax(z)
min = torch.argmin(z)
max, min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [146]:
torch.manual_seed(7)
random_tensor = torch.rand(1,1,1,10)
random_tensor, random_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [147]:
new_tensor = random_tensor.squeeze(0,1,2)
random_tensor, random_tensor.shape, new_tensor, new_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))