<a href="https://colab.research.google.com/github/tranviviana/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)



2.3.0+cu121


###**Introduction to Tensors**###


Creating Tensors

In [2]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim


0

In [4]:
#conver tensor to python int
scalar.item()

7

In [5]:
#vector notation
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
#dimension correlates to number of square brackets
vector.ndim

1

In [9]:
#number of elements in square brackets
vector.shape

torch.Size([2])

In [10]:
vector2 = torch.tensor([7,7,7,7])
vector2

tensor([7, 7, 7, 7])

In [13]:
vector2.ndim

1

In [14]:
vector2.shape

torch.Size([4])

In [17]:
# matrix styles
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX[0]

tensor([7, 8])

In [20]:
MATRIX[0][0]

tensor(7)

In [21]:
MATRIX[0][0].item()


7

In [22]:
MATRIX.shape

torch.Size([2, 2])

In [24]:
#tensors
TENSOR = torch.tensor([[[1,2,3], [3,6,9], [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [25]:
TENSOR.ndim

3

In [27]:
TENSOR.shape

torch.Size([1, 3, 3])

In [28]:
#outermost bracket matches here
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [30]:
TENSOR[0][1]

tensor([3, 6, 9])

In [43]:
TENSOR2 = torch.tensor([[[[1,2,3,8],[7,4,5,6],[2,3,4,5],[2,3,0,5]]]])
TENSOR2

tensor([[[[1, 2, 3, 8],
          [7, 4, 5, 6],
          [2, 3, 4, 5],
          [2, 3, 0, 5]]]])

In [44]:
TENSOR2.ndim

4

In [45]:
TENSOR2.shape

torch.Size([1, 1, 4, 4])

In [46]:
TENSOR2[0]

tensor([[[1, 2, 3, 8],
         [7, 4, 5, 6],
         [2, 3, 4, 5],
         [2, 3, 0, 5]]])

In [47]:
TENSOR2[0][0]

tensor([[1, 2, 3, 8],
        [7, 4, 5, 6],
        [2, 3, 4, 5],
        [2, 3, 0, 5]])

In [48]:
TENSOR2[0][0][0]

tensor([1, 2, 3, 8])

###**CREATING RANDOM TENSORS**###

random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data`

In [67]:
#creating random tensors of size(3,4)
random_tensor = torch.rand(8,2,2) #8 groups of 2 by 2
random_tensor


tensor([[[0.8291, 0.8583],
         [0.2662, 0.3340]],

        [[0.4590, 0.8521],
         [0.1445, 0.4929]],

        [[0.7668, 0.5998],
         [0.3578, 0.1779]],

        [[0.8567, 0.1144],
         [0.4588, 0.8140]],

        [[0.7816, 0.2904],
         [0.9041, 0.7434]],

        [[0.5843, 0.6508],
         [0.6140, 0.0777]],

        [[0.7280, 0.8630],
         [0.2616, 0.7565]],

        [[0.8582, 0.6370],
         [0.0155, 0.3721]]])

In [70]:
random_tensor.ndim,random_tensor[0]

(3,
 tensor([[0.8291, 0.8583],
         [0.2662, 0.3340]]))

In [53]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height width color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [74]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [75]:
tensor.ndim

1

In [76]:
tensor[0]

tensor(1)

###**Zeros and Ones**###

In [77]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [81]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6678, 0.4244, 0.5579, 0.9761],
        [0.8649, 0.6772, 0.0500, 0.6208],
        [0.5304, 0.3713, 0.5515, 0.6130]])

In [82]:
random_tensor * zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])